### ISSUE TITLE
2D Models (Z-shaped and Spiral) data gen implementation on datagen.py module

### ISSUE THREAD

**Issue by pedrojuanbj** [pedrojuanbj/MLTSA#2]
We need to implement the 2D data generation classes and the projection to 1D suite in a single module inside MLTSA_datasets under the 2D folder, the name of the module can be anything but something related to it like datagen.py or datagen_2D.py is good.  

For this implementation to be shipped we need to add the latest data generation code on the models, we could have some optional plots for the free energy surface of the potentials, also it should be implemented as a module call similar to the 1D one to generate data on demand as it is really fast and optimized now. Additionally the 1D projection code should be added to it to provide the data ready for train on demand as well.

**Comment by zwei21** [comment]
### This is self assigned to @zwei21 now, following is a typical blueprint for output closing this issue:  
#### Demand Analysis:  
- **WHAT**: The aim of this work is to set a data pipeline for generating data from 2D potential, along with any handy functions equiped with it.  
- **WHO**: This issue has been self assigned to @zwei21, represented as "this author" in the following parts unless particularly mentioned.  
- **WHERE**: The 2D potential, so far by this post edited, is in consist of two part, the Z-shape potential and the Spiral potential, each would expect an individual class for data generation.  
- **HOW**: The generated data is in manner of **projected** **trajectories**, which are simulated by principle of molecular dynamics(MD). _in details, **the generation principle is based on work of Valdimir and Pedro**, this author would concentrate on transfering and implementing the code to produce it, the credit on MD principle should not be given to this author @zwei21._  
- **WHY**: The output data would be used for feeding models including deep learning and other machine learning algorithms, in order to analyse the feature importance variations.
- **WHEN**: The project to close this issue has began at Nov. 2021, so far by this post edited, this issue is estimated to be closed no later than **Jun. 27th, 2022.**

**Comment by zwei21** [comment]
#### Data Pipeline:

1. Implementing the potential function generation of Z-shape and Spiral;  
2. Simulation on potential surface generated by step 1, producing trajectories;  
3. Cleaning, labelling the trajectories generated by step2, producing balanced, clean data for projection;  
4. Making proper projection on trajectories selected by step3, transfering the data in shape of fitted for feeding the MLTSA models.  

#### List of TODOs:  
  
- [ ] 1.1 [**Class or Function**] Spiral potential generation  
- [ ] 1.2 [**Class or Function**] Z-shape potential generation  
- [ ] 1.3 [**Function**] Visulisation of potential surfaces, in 3D axis.  
---    
- [ ] 2.1 [**Class or Function**] Langevin trajectory generation, both Z-shape and Spiral  
- [ ] 2.2 [**Function**] Visualisation of trajectories, 2D plot.  
- [ ] 2.3 [**Function**] Visualisation of trajectories with respect to 3D potential surfaces(intuitive vision)  
---  
- [ ] 3.1 [**Class**] DataPreprocess, including the following functions:  
- [ ] 3.1.1 [**Function**] Data Labelling, processing the trajectories generated in step 2, based on DBSCAN  
- [ ] 3.1.2 [**Function**] Data Cleaning, processing the labelled data by 3.1.1, cleaning out any outliners  
- [ ] 3.1.3 [**Function**] Data Filtering, processing the cleaned data by 3.1.2, balancing the data amount with respected to data labels, producing even distributed trajectory data. _Intuitively, this means prodcing same amount of data for each valid label cluster after cleaning data._  
- [ ] 3.2 [**Class or Function**] Visualisation of 3.1 steps, for debugging use.  
---  
- [ ] 4.1 [**Class or Function**] Projection with respect to trajectories, in manner of **axis rotation**  
- [ ] 4.2 [**Function**] Visualisation of projection, for debugging use.  
---  
- [ ] 5.1 [**Class or Function**] Unit test for step 1;  
- [ ] 5.2 [**Class or Function**] Unit test for step 2;  
- [ ] 5.3 [**Class or Function**] Unit test for step 3;  
- [ ] 5.4 [**Class or Function**] Unit test for step 4;  
- [ ] 5.5 [**Class or Function**] Integration test for data pipeline built above;  
---  
- [ ] 6.0 [**Class**] Lite-Version of producing data in manner of a single jupyter notebook file.  

#### Plan of File Structure(key files only):
```Bash
../2DPot
  | _ _ /src
  |        | _ _ /potentials
  |        |       | _ _ spiral.py
  |        |       | _ _ zshape.py
  |        | _ _generateTraj.py
  |        | _ _dataprocess.py
  | _ _ /test
  | _ _ /build
          | _ _liteSpiral.ipynb
          | _ _liteZshape.ipynb
```

**Comment by zwei21** [comment]
Curie is not stable recent days, which affect the normal pace of developing on it, would delay for few days but sure would finish the main code by end of June.

**Comment by pedrojuanbj** [comment]
> Curie is not stable recent days, which affect the normal pace of developing on it, would delay for few days but sure would finish the main code by end of June.

I think Sascha is running MLTSA on some protein data and is blasting the computer, I can ask him to move to a cluster, but it should not be long until they finish .

**Comment by zwei21** [comment]
This issue is fullfilled per pull request #14 
Closing commit 7e34aea4cacd5612529f33a1a443cfbd3dc143ca
Further features and development, including code enhancement and unittest, would be merged to new issues.
